server:
  port: 8080

spring:
  application:
    name: bank-service
  datasource:
    url: jdbc:sqlserver://bank-service-db:1433;databaseName=BANK_SERVICE
    username: sa
    password: bank-service-password
    hikari:
      maximum-pool-size: 150
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl.auto: update
        format_sql: true
        dialect:  org.hibernate.dialect.SQLServer2016Dialect
        cache.use_second_level_cache: false
        connection.isolation: 4096
        connection.useUnicode: true
        connection.characterEncoding: utf-8
        connection.CharSet: utf-8
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

bank-service:
  jwt:
    keyStorePath: keyStore.jks
    keyStorePassword: mfcatl007
    keyAlias: keypairname
    privateKeyPassphrase: mfcatl007
    issuer: lcms
