CREATE DATABASE BANK_SERVICE;

ALTER DATABASE BANK_SERVICE SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE BANK_SERVICE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE BANK_SERVICE SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE BANK_SERVICE SET MULTI_USER;